In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
file_path = r"E:\Data Analyst Internship\E-commerce Return Rate Reduction Analysis\Dataset\returns_sustainability_dataset.csv"
df = pd.read_csv(file_path)
df.head()

,Order_ID,Product_ID,User_ID,Order_Date,Product_Category,Product_Price,Order_Quantity,Discount_Applied,Shipping_Method,Payment_Method,...,Return_Status,Return_Reason,Days_to_Return,Order_Value,Return_Cost,Profit_Loss,CO2_Emissions,Packaging_Waste,CO2_Saved,Waste_Avoided
0,ORD00000,PROD0169,USER0195,2022-01-14,Clothing,1720.71,2,30.46,Next-Day,Wallet,...,Not Returned,No Return,0,2393.163468,0,2393.163468,2.0,0.4,2.0,0.4
1,ORD00001,PROD0318,USER1469,2022-01-03,Toys,744.06,5,29.62,Next-Day,Wallet,...,Returned,Size Issue,12,2618.347140,200,2418.347140,2.0,1.0,0.0,0.0
2,ORD00002,PROD0427,USER1812,2025-03-16,Clothing,983.68,5,47.80,Express,Wallet,...,Not Returned,No Return,0,2567.404800,0,2567.404800,1.5,1.0,1.5,1.0
3,ORD00003,PROD0323,USER1274,2024-11-06,Books,1855.65,2,2.90,Express,COD,...,Not Returned,No Return,0,3603.672300,0,3603.672300,1.5,0.4,1.5,0.4
4,ORD00004,PROD0325,USER0551,2023-06-07,Home Appliances,1770.97,5,44.42,Express,COD,...,Returned,Size Issue,11,4921.525630,200,4721.525630,1.5,1.0,0.0,0.0

In [5]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 5000
Number of columns: 23

In [9]:
df.isnull().sum()

Order_ID            0
Product_ID          0
User_ID             0
Order_Date          0
Product_Category    0
Product_Price       0
Order_Quantity      0
Discount_Applied    0
Shipping_Method     0
Payment_Method      0
User_Age            0
User_Gender         0
User_Location       0
Return_Status       0
Return_Reason       0
Days_to_Return      0
Order_Value         0
Return_Cost         0
Profit_Loss         0
CO2_Emissions       0
Packaging_Waste     0
CO2_Saved           0
Waste_Avoided       0
dtype: int64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
df.dtypes

Order_ID             object
Product_ID           object
User_ID              object
Order_Date           object
Product_Category     object
Product_Price       float64
Order_Quantity        int64
Discount_Applied    float64
Shipping_Method      object
Payment_Method       object
User_Age              int64
User_Gender          object
User_Location        object
Return_Status        object
Return_Reason        object
Days_to_Return        int64
Order_Value         float64
Return_Cost           int64
Profit_Loss         float64
CO2_Emissions       float64
Packaging_Waste     float64
CO2_Saved           float64
Waste_Avoided       float64
dtype: object

In [12]:
df.describe()

,Product_Price,Order_Quantity,Discount_Applied,User_Age,Days_to_Return,Order_Value,Return_Cost,Profit_Loss,CO2_Emissions,Packaging_Waste,CO2_Saved,Waste_Avoided
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000
mean,1054.294740,2.997600,25.011476,41.551800,9.204200,2366.996469,58.000000,2308.996469,1.500100,0.599520,1.066600,0.42668
std,548.560406,1.400709,14.430681,13.890195,16.753156,1834.851991,90.761487,1838.461511,0.410346,0.280142,0.764448,0.36150
min,100.090000,1.000000,0.000000,18.000000,0.000000,52.165727,0.000000,-147.834273,1.000000,0.200000,0.000000,0.00000
25%,580.937500,2.000000,12.827500,30.000000,0.000000,928.078449,0.000000,863.905130,1.000000,0.400000,0.000000,0.00000
50%,1044.850000,3.000000,25.020000,42.000000,0.000000,1864.584054,0.000000,1808.077845,1.500000,0.600000,1.000000,0.40000
75%,1530.835000,4.000000,37.380000,54.000000,12.000000,3382.309799,200.000000,3345.675860,2.000000,0.800000,1.500000,0.80000
max,1999.800000,5.000000,50.000000,65.000000,60.000000,9827.017200,200.000000,9827.017200,2.000000,1.000000,2.000000,1.00000

In [13]:
print(df["Order_Date"].dtype)

object

In [14]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    dayfirst=True
)

C:\Users\rohin\AppData\Local\Temp\ipykernel_5364\3115949413.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Order_Date"] = pd.to_datetime(

In [15]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], dayfirst=False)

In [16]:
print(df["Order_Date"].dtype)

datetime64[ns]

In [17]:
print("Start Date:", df["Order_Date"].min())
print("End Date:", df["Order_Date"].max())

Start Date: 2022-01-01 00:00:00
End Date: 2025-09-03 00:00:00

In [18]:
df["Return_Status"].value_counts()

Return_Status
Not Returned    3550
Returned        1450
Name: count, dtype: int64

In [19]:
df["Return_Reason"].value_counts()

Return_Reason
No Return       3550
Defective        382
Changed Mind     379
Wrong Item       348
Size Issue       341
Name: count, dtype: int64